from django.urls import path
from . import views

urlpatterns = [
    path('users/', views.UserProfileListCreateView.as_view(), name='userprofile-list'),
    path('users/<int:pk>/', views.UserProfileDetailView.as_view(), name='userprofile-detail'),
    path('products/', views.ProductListCreateView.as_view(), name='product-list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('strequests/', views.STRequestListCreateView.as_view(), name='strequest-list'),
    path('strequests/<int:pk>/', views.STRequestDetailView.as_view(), name='strequest-detail'),
    path('user-info/', views.UserInfoView.as_view(), name='user-info'),
    path('user/on-work/', views.UpdateOnWorkView.as_view(), name='update-on-work'),
    path('photographer-requests/', views.PhotographerSTRequestListView.as_view(), name='photographer-requests'),
    path('photographer-request/<str:request_number>/', views.PhotographerSTRequestDetailView.as_view(), name='photographer-request-detail'),
    path('photographercamera/', views.CameraListView.as_view(), name='photographercamera-list'),
    path("photographerproduct/<str:barcode>/", views.PhotographerProductView.as_view(), name="photographer-product"),
    path('photographer/update-product-status/', views.PhotographerUpdateProductView.as_view(), name='photographer-update-product-status'),
    path('sphotographer/requests/', views.SPhotographerRequestsListView.as_view(), name='sphotographer-requests'),
    path('photo_status_list/', views.PhotoStatusListView.as_view(), name='photo-status-list'),
    path('sphoto_status_list/', views.SPhotoStatusListView.as_view(), name='sphoto-status-list'),
    path('sphotographer/request-detail/', views.SPhotographerRequestDetailView.as_view(), name='sphotographer-request-detail'),
    path('sphotographer/onwork-photographers/', views.OnWorkPhotographersListView.as_view(), name='onwork-photographers'),
    path('upcoming-birthdays/', views.upcoming_birthdays, name='upcoming_birthdays'),
    path('create-photo-time/', views.CreateSTRequestPhotoTimeView.as_view(), name='create-photo-time'),
    path('get-photo-times/', views.GetPhotoTimesByRequestNumberView.as_view(), name='get_photo_times'),
    path('start-shooting/', views.StartShootingView.as_view(), name='start_shooting'),
    path('server-time/', views.server_time, name='server_time'),
    path('sr/ready-products/', views.SRReadyProductsListView.as_view(), name='sr_ready_products'),
    path('sr/create-retouch-request/', views.SRRetouchRequestCreateView.as_view(), name='sr_create_retouch_request'),
    path('ready-photos/', views.ReadyPhotosListView.as_view(), name='ready-photos-list'),
    path('sr-statistic/', views.SRStatisticView.as_view(), name='sr-statistic'),
    path('stockman_income/', views.stockman_income, name='stockman_income'),
    path('stockman_outcome/', views.stockman_outcome, name='stockman_outcome'),
    path('stockman_defect/', views.stockman_defect, name='stockman_defect'),
    path('stockman_opened/', views.stockman_opened, name='stockman_opened'),
    path('stockman_create_strequest/', views.strequest_create, name='create_strequest'),
    path('nofoto/', views.nofoto_create, name='nofoto_create'),
    path('sp/assistants/', views.sp_get_assistants, name='get_assistants'),
    path('sp/assign-assistant/', views.sp_assign_assistant, name='assign_assistant'),
    path('sp/clear-assistant/', views.sp_clear_assistant, name='clear_assistant'),
    path('sp/daily_stats/', views.sp_daily_stats, name='daily_stats'),
    path('product-operations/', views.ProductOperationListView.as_view(), name='product-operation-list'),
    path('product-operation-types/', views.ProductOperationTypesListView.as_view(), name='product-operation-types-list'),
]
