# Generated by Django 5.1.2 on 2025-03-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.CharField(max_length=13, unique=True)),
                ('ProductID', models.BigIntegerField(blank=True, null=True)),
                ('SKUID', models.BigIntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=500)),
                ('CategoryName', models.CharField(blank=True, max_length=64, null=True)),
                ('CategoryID', models.BigIntegerField(blank=True, null=True)),
                ('ShopID', models.BigIntegerField(blank=True, null=True)),
                ('ShopType', models.CharField(blank=True, max_length=4, null=True)),
                ('ShopName', models.CharField(blank=True, max_length=64, null=True)),
                ('ProductStatus', models.CharField(blank=True, max_length=64, null=True)),
                ('ProductModerationStatus', models.CharField(blank=True, max_length=64, null=True)),
                ('SKUStatus', models.CharField(blank=True, max_length=64, null=True)),
                ('WMSQuantity', models.BigIntegerField(blank=True, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
