# Generated by Django 5.1.2 on 2025-03-20 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedReason',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RenderCheckResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetouchStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorRetouchStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='IsModerationBlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='IsRetouchBlock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ModerationComment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ModerationCommentTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RejectComment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RejectCommentTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RetouchComment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RetouchCommentDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RetouchSeniorComment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='RetouchSeniorCommentTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckTimeStart', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала проверки')),
                ('CheckTimeEnd', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания проверки')),
                ('CheckComment', models.TextField(blank=True, null=True)),
                ('RetouchTimeStart', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала рендера')),
                ('RetouchTimeEnd', models.DateTimeField(blank=True, null=True, verbose_name='Дата загрузки фото')),
                ('RetouchPhotosLink', models.CharField(blank=True, max_length=512, null=True)),
                ('RetouchComment', models.TextField(blank=True, null=True)),
                ('RetouchSeniorComment', models.TextField(blank=True, null=True)),
                ('ModerationComment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('Retoucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ретушёр')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.product')),
                ('CheckResult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.rendercheckresult')),
                ('RetouchStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.retouchstatus')),
                ('RetouchSeniorStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.seniorretouchstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ModerationUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadTimeStart', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала модерации')),
                ('UploadTimeEnd', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания модерации')),
                ('UploadTime', models.DurationField(blank=True, null=True, verbose_name='Длительность модерации')),
                ('IsUploaded', models.BooleanField(default=False)),
                ('RejectComment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('Moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('RejectedReason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.rejectedreason', verbose_name='Причина отклонения')),
                ('RenderPhotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='render.render')),
            ],
        ),
    ]
