# Generated by Django 5.1.2 on 2025-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_rejectedreason_rendercheckresult_retouchstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='render',
            old_name='product',
            new_name='Product',
        ),
        migrations.AddField(
            model_name='moderationupload',
            name='IsRejected',
            field=models.BooleanField(default=False, verbose_name='Отклонено'),
        ),
        migrations.AddField(
            model_name='product',
            name='PhotoModerationStatus',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='render',
            name='CheckDuration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность проверки'),
        ),
        migrations.AddField(
            model_name='render',
            name='RetouchDuration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность рендера'),
        ),
        migrations.AlterField(
            model_name='moderationupload',
            name='IsUploaded',
            field=models.BooleanField(default=False, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='priority',
            field=models.IntegerField(default=10),
        ),
    ]
