# Generated by Django 5.1.2 on 2025-03-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_rename_product_render_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationupload',
            name='RejectedReason',
        ),
        migrations.RemoveField(
            model_name='render',
            name='CheckResult',
        ),
        migrations.AddField(
            model_name='moderationupload',
            name='RejectedReason',
            field=models.ManyToManyField(blank=True, to='render.rejectedreason', verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='render',
            name='CheckResult',
            field=models.ManyToManyField(blank=True, to='render.rendercheckresult', verbose_name='Результат проверки'),
        ),
    ]
