# Generated by Django 5.1.2 on 2025-03-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0004_remove_moderationupload_rejectedreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='render',
            name='IsSuitable',
            field=models.BooleanField(null=True, verbose_name='Подходит для рендера'),
        ),
        migrations.AlterField(
            model_name='moderationupload',
            name='IsRejected',
            field=models.BooleanField(null=True, verbose_name='Отклонено'),
        ),
        migrations.AlterField(
            model_name='moderationupload',
            name='IsUploaded',
            field=models.BooleanField(null=True, verbose_name='Загружено'),
        ),
    ]
