# Generated by Django 5.1.2 on 2025-03-21 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0005_render_issuitable_alter_moderationupload_isrejected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='IsOnRender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='render',
            name='IsOnUpload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderationupload',
            name='UploadStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.uploadstatus', verbose_name='Статус загрузки'),
        ),
    ]
