# Generated by Django 5.1.2 on 2025-03-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0006_uploadstatus_product_isonrender_render_isonupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationupload',
            name='ReturnToRender',
            field=models.BooleanField(null=True, verbose_name='Вернуть ретушерам'),
        ),
    ]
