# Generated by Django 5.1.2 on 2025-04-08 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_retouchrequestproduct_isonupload_and_more'),
        ('render', '0007_moderationupload_returntorender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioRejectedReason',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='moderationupload',
            name='ReturnToRenderComplete',
            field=models.BooleanField(default=False, verbose_name='Ретушеры забрали'),
        ),
        migrations.AddField(
            model_name='product',
            name='IsOnOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moderationupload',
            name='ReturnToRender',
            field=models.BooleanField(default=False, verbose_name='Вернуть ретушерам'),
        ),
        migrations.AlterField(
            model_name='moderationupload',
            name='UploadTime',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность загрузки'),
        ),
        migrations.AlterField(
            model_name='moderationupload',
            name='UploadTimeEnd',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания загрузки'),
        ),
        migrations.AlterField(
            model_name='moderationupload',
            name='UploadTimeStart',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала загрузки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ShopName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='ModerationStudioUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UploadTimeStart', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала загрузки')),
                ('UploadTimeEnd', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания загрузки')),
                ('UploadTime', models.DurationField(blank=True, null=True, verbose_name='Длительность загрузки')),
                ('IsUploaded', models.BooleanField(null=True, verbose_name='Загружено')),
                ('IsRejected', models.BooleanField(null=True, verbose_name='Отклонено')),
                ('RejectComment', models.TextField(blank=True, null=True)),
                ('ReturnToRender', models.BooleanField(default=False, verbose_name='Вернуть ретушерам')),
                ('ReturnToRenderComplete', models.BooleanField(default=False, verbose_name='Ретушеры забрали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('Moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('RenderPhotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.retouchrequestproduct')),
                ('UploadStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='render.uploadstatus', verbose_name='Статус загрузки')),
                ('RejectedReason', models.ManyToManyField(blank=True, to='render.studiorejectedreason', verbose_name='Причина отклонения')),
            ],
        ),
    ]
