# Generated by Django 5.1.2 on 2025-06-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0008_studiorejectedreason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ShopName',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
