# Generated by Django 5.1.2 on 2025-05-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RGTScripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OKZReorderEnable', models.BooleanField(default=True, verbose_name='Сброс заказов ОКЗ')),
                ('OKZReorderTreshold', models.DurationField(blank=True, null=True, verbose_name='Отсечка сброса')),
                ('OldProductsPriorityEnable', models.BooleanField(default=True, verbose_name='Выставление приоритетов по времени приемки')),
                ('OldProductsPriorityTreshold', models.DurationField(blank=True, null=True, verbose_name='Отсечка выставления приоритетов')),
            ],
            options={
                'verbose_name': 'Настройки управления скриптами РГТ',
                'verbose_name_plural': 'Настройки управления скриптами',
            },
        ),
    ]
