# Generated by Django 5.1.1 on 2025-06-20 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_retouchrequestproduct_retouch_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetouchRequestEdits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('RetouchRequestProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.retouchrequestproduct')),
                ('SeniorRetoucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Старший_ретушер', to=settings.AUTH_USER_MODEL)),
                ('retoucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Ретушер', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
